server:
  port: 8081 # web port 가 곂치는 것을 피하고자.

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  batch:
    job:             # 기본값 true 는 Spring Boot 실행시 등록되어 있는 Job 들이 실행됨
      enabled: false # 현재 Job 관련 기능 구현 에서 REST API 를 적용할 것이므로 false 처리해야.
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default

kakaotalk:
  host: https://kapi.kakao.com
  token: YOUR_ACCESS_TOKEN